apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: base
build:
  local:
    push: false
  artifacts:
    - image: base-builder
      docker:
        dockerfile: cmd/Dockerfile

---
apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: boilerplate

build:
  artifacts:
    - image: some-registry/api
      docker:
        dockerfile: cmd/api/Dockerfile
      requires:
        - image: base-builder
          alias: BASE_BUILDER
  local:
    concurrency: 0 # 0 concurrency means run all in parallel, could probably tune this if the number of services grows
  tagPolicy:
    gitCommit: {}

deploy:
  helm:
    releases:
      - name: api
        chartPath: charts/api
        artifactOverrides:
          api.image: some-registry/api
        imageStrategy:
          helm:
            explicitRegistry: true

profiles:
  - name: local
    activation:
      - command: debug
    deploy:
      kubeContext: kind-boilerplate

    portForward:
      - resourceType: Service
        resourceName: api
        port: 80
        localPort: 9000
